### ISSUE TITLE
Can't upgrade to the latest version 0.6.2

### ISSUE THREAD

**Issue by Hiieu** [maxcountryman/flask-bcrypt#26]
'Upgrade packages failed.

The following command was executed:

packaging_tool.py install --build-dir C:\Users\HP\AppData\Local\Temp\pycharm-packaging1541100851476301310.tmp -U Flask-Bcrypt

The error output of the command:

DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Requirement already up-to-date: Flask-Bcrypt in c:\users\hp\dropbox\venv\lib\site-packages
Requirement already up-to-date: Flask in c:\users\hp\dropbox\venv\lib\site-packages (from Flask-Bcrypt)
Downloading/unpacking py-bcrypt (from Flask-Bcrypt)
  Downloading py-bcrypt-0.4.tar.gz
  Running setup.py (path:C:\Users\HP\AppData\Local\Temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\setup.py) egg_info for package py-bcrypt
    
Requirement already up-to-date: Werkzeug>=0.7 in c:\users\hp\dropbox\venv\lib\site-packages (from Flask->Flask-Bcrypt)
Requirement already up-to-date: Jinja2>=2.4 in c:\users\hp\dropbox\venv\lib\site-packages (from Flask->Flask-Bcrypt)
Requirement already up-to-date: itsdangerous>=0.21 in c:\users\hp\dropbox\venv\lib\site-packages (from Flask->Flask-Bcrypt)
Requirement already up-to-date: markupsafe in c:\users\hp\dropbox\venv\lib\site-packages (from Jinja2>=2.4->Flask->Flask-Bcrypt)
Installing collected packages: py-bcrypt
  Running setup.py install for py-bcrypt
    building 'bcrypt._bcrypt' extension
    c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/bcrypt.c /Fobuild\temp.win32-2.7\Release\bcrypt/bcrypt.obj
    bcrypt.c
    bcrypt/bcrypt.c(139) : warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdio.h(358) : see declaration of '_snprintf'
    bcrypt/bcrypt.c(249) : warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
            c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdio.h(358) : see declaration of '_snprintf'
    c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/bcrypt_pbkdf.c /Fobuild\temp.win32-2.7\Release\bcrypt/bcrypt_pbkdf.obj
    bcrypt_pbkdf.c
    c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/bcrypt_python.c /Fobuild\temp.win32-2.7\Release\bcrypt/bcrypt_python.obj
    bcrypt_python.c
    bcrypt/bcrypt_python.c(63) : warning C4244: 'function' : conversion from 'long' to 'u_int8_t', possible loss of data
    c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/blowfish.c /Fobuild\temp.win32-2.7\Release\bcrypt/blowfish.obj
    blowfish.c
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2146: syntax error : missing ')' before identifier 'passlen'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2081: 'size_t' : name in formal parameter list illegal
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2061: syntax error : identifier 'passlen'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2059: syntax error : ';'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2059: syntax error : ','
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(88) : error C2059: syntax error : ')'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2146: syntax error : missing ')' before identifier 'n'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2081: 'size_t' : name in formal parameter list illegal
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2061: syntax error : identifier 'n'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2059: syntax error : ';'
    c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2059: syntax error : ')'
    error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2
    Complete output from command C:\Users\HP\Dropbox\venv\Scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pycharm-packaging1541100851476301310.tmp\\py-bcrypt\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\hp\appdata\local\temp\pip-xbpywi-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\HP\Dropbox\venv\include\site\python2.7:
    running install

running build

running build_py

creating build

creating build\lib.win32-2.7

creating build\lib.win32-2.7\bcrypt

copying bcrypt\__init__.py -> build\lib.win32-2.7\bcrypt

running build_ext

building 'bcrypt._bcrypt' extension

creating build\temp.win32-2.7

creating build\temp.win32-2.7\Release

creating build\temp.win32-2.7\Release\bcrypt

c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/bcrypt.c /Fobuild\temp.win32-2.7\Release\bcrypt/bcrypt.obj

bcrypt.c

bcrypt/bcrypt.c(139) : warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdio.h(358) : see declaration of '_snprintf'

bcrypt/bcrypt.c(249) : warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdio.h(358) : see declaration of '_snprintf'

c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/bcrypt_pbkdf.c /Fobuild\temp.win32-2.7\Release\bcrypt/bcrypt_pbkdf.obj

bcrypt_pbkdf.c

c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/bcrypt_python.c /Fobuild\temp.win32-2.7\Release\bcrypt/bcrypt_python.obj

bcrypt_python.c

bcrypt/bcrypt_python.c(63) : warning C4244: 'function' : conversion from 'long' to 'u_int8_t', possible loss of data

c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Users\HP\Dropbox\venv\PC /Tcbcrypt/blowfish.c /Fobuild\temp.win32-2.7\Release\bcrypt/blowfish.obj

blowfish.c

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2146: syntax error : missing ')' before identifier 'passlen'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2081: 'size_t' : name in formal parameter list illegal

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2061: syntax error : identifier 'passlen'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2059: syntax error : ';'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2059: syntax error : ','

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(88) : error C2059: syntax error : ')'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2146: syntax error : missing ')' before identifier 'n'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2081: 'size_t' : name in formal parameter list illegal

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2061: syntax error : identifier 'n'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2059: syntax error : ';'

c:\users\hp\appdata\local\temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2059: syntax error : ')'

error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2

----------------------------------------
Cleaning up...
Command C:\Users\HP\Dropbox\venv\Scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pycharm-packaging1541100851476301310.tmp\\py-bcrypt\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\hp\appdata\local\temp\pip-xbpywi-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\HP\Dropbox\venv\include\site\python2.7 failed with error code 1 in C:\Users\HP\AppData\Local\Temp\pycharm-packaging1541100851476301310.tmp\py-bcrypt
Storing debug log for failure in C:\Users\HP\pip\pip.log'

**Comment by maxcountryman** [comment]
It's working now I believe.
