### ISSUE TITLE
problems when install flask-bcrypt on windows 32 bits and python3.4

### ISSUE THREAD

**Issue by xmnlab** [maxcountryman/flask-bcrypt#27]
Hi dear friends,

I'm using the flask-bcrypt after I've started to use flask-cookiecutter  
it is a good lib, but now I've have problems to install it on a windows 32 bits and with python 3.4.

the python-bcrypt seems to be out dated.

Do you have some recommendation to install flask-bcrypt on this environment?

The python-bcrypt doesn't have any update since 2014-07-22  ... I saw other bcrypt implementation called bcrypt .. and that seems to be updated recently .. do you have some plan to migrate the bcrypt library?

My best regards,

**Comment by maxcountryman** [comment]
I certainly don't mind migrating to a more recent bcrypt implementation if it fixes your issues. Have you tried this locally?

**Comment by xmnlab** [comment]
Hi @maxcountryman, 

In my environment I can install bcrypt with pip with no problem.

I install bcrypt on linux 64 with no problem too.

But I have no experience with bcrypt ...

**Comment by maxcountryman** [comment]
What's the exact problem you have installing flask-bcrypt? Can you provide a traceback?

**Comment by xmnlab** [comment]
the problem is when try to install python-bcrypt ... the old problem with vcvarsall ...

```log
C:\Documents and Settings\Usuario>pip install flask-bcrypt
Collecting flask-bcrypt
Collecting python-bcrypt (from flask-bcrypt)
  Using cached python-bcrypt-0.3.1.zip
Requirement already satisfied (use --upgrade to upgrade): Flask in c:\miniconda3
\lib\site-packages (from flask-bcrypt)
Building wheels for collected packages: python-bcrypt
  Running setup.py bdist_wheel for python-bcrypt
  Complete output from command C:\Miniconda3\python.exe -c "import setuptools;__
file__='C:\\DOCUME~1\\Usuario\\CONFIG~1\\Temp\\pip-build-9ld8_zol\\python-bcrypt
\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__,
'exec'))" bdist_wheel -d C:\DOCUME~1\Usuario\CONFIG~1\Temp\tmpewu2be0ypip-wheel-
:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.4
  creating build\lib.win32-3.4\bcrypt
  copying bcrypt\__init__.py -> build\lib.win32-3.4\bcrypt
  running build_ext
  building 'bcrypt._bcrypt' extension
  error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

  ----------------------------------------
  Failed building wheel for python-bcrypt
Failed to build python-bcrypt
Installing collected packages: python-bcrypt, flask-bcrypt
  Running setup.py install for python-bcrypt
    Complete output from command C:\Miniconda3\python.exe -c "import setuptools,
 tokenize;__file__='C:\\DOCUME~1\\Usuario\\CONFIG~1\\Temp\\pip-build-9ld8_zol\\p
ython-bcrypt\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).r
ead().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\DOCUME~1\Us
uario\CONFIG~1\Temp\pip-cnoq3xu4-record\install-record.txt --single-version-exte
rnally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'bcrypt._bcrypt' extension
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).


    ----------------------------------------
Command "C:\Miniconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\
DOCUME~1\\Usuario\\CONFIG~1\\Temp\\pip-build-9ld8_zol\\python-bcrypt\\setup.py';
exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\
n'), __file__, 'exec'))" install --record C:\DOCUME~1\Usuario\CONFIG~1\Temp\pip-
cnoq3xu4-record\install-record.txt --single-version-externally-managed --compile
" failed with error code 1 in C:\DOCUME~1\Usuario\CONFIG~1\Temp\pip-build-9ld8_z
ol\python-bcrypt
```

**Comment by maxcountryman** [comment]
Can you try using python-crypt 0.4 instead?

**Comment by xmnlab** [comment]
with py-bcrypt give me the same error .. problem with vcvarsall.bat ...

**Comment by maxcountryman** [comment]
On their website it says py-bcrypt 0.4 fixed some Windows compilations errors. Are you sure that doesn't work?

**Comment by xmnlab** [comment]
Yes :( .. it's not working ... 
and I've found a binstar to win32 .. but just for python27 ...

**Comment by maxcountryman** [comment]
Can you open up a bug report with py-bcrypt about this?

**Comment by xmnlab** [comment]
Hi @maxcountryman ok :) thank you!

**Comment by xmnlab** [comment]
https://code.google.com/p/py-bcrypt/issues/detail?id=19

done!

**Comment by xmnlab** [comment]
I have no answer at this moment on py-bcrypt google code platform ...

**Comment by maxcountryman** [comment]
Okay, I'd give them a few days to respond. For the time being I'm not able to do much. Let me know if you hear more from them.

**Comment by xmnlab** [comment]
Okay, thank you!! :)

**Comment by growingdever** [comment]
I met same error.

**Comment by maxcountryman** [comment]
I believe `0.7.0` should fix this.
