### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by ser** [maxcountryman/flask-bcrypt#28]
password = b'super secret password'
hashpw= b'$2b$12$iyUDXZ.BX0jV2xfdZI7Ame4BB1lkIrZILNPe3Nax4gUMnqWU9lAv2'

```
  File "/home/ser/GIT/topitup/login_bp.py", line 82, in index
    if username and bcrypt_flask.check_password_hash(pwhash, password):
  File "/usr/lib/python3.4/site-packages/flask_bcrypt.py", line 180, in check_password_hash
    return safe_str_cmp(bcrypt.hashpw(password, pw_hash), pw_hash)
  File "/usr/lib/python3.4/site-packages/bcrypt/__init__.py", line 139, in hashpw
    raise TypeError("Unicode-objects must be encoded before hashing")
TypeError: Unicode-objects must be encoded before hashing
```
Python 3.4.3 (default, Mar 25 2015, 17:13:50)

**Comment by maxcountryman** [comment]
Looks like you need to encode the password before hashing.

**Comment by ser** [comment]
It's encoded. Clean bcrypt handles it without any issue.

**Comment by maxcountryman** [comment]
Unfortunately I don't use Python 3 at all, so I can't really provide much help directly. Feel free to investigate and I'll gladly merge any appropriate fixes you might have.

**Comment by ser** [comment]
My investigation made clear that flask-bcrypt is useless and makes things much more complicated and code longer and less clear. I would suggest removal of this extension.

**Comment by maxcountryman** [comment]
I don't see how comments like that are helpful or constructive to anyone.
