### ISSUE TITLE
Broken with Bcrypt 2.0.0

### ISSUE THREAD

**Issue by sphildreth** [maxcountryman/flask-bcrypt#33]
The "check_password_hash" method throws an error:
    TypeError: hashpw() argument 1 must be str, not bytes

If you comment out lines 180 to 191 in "flask_bcrypt.py" it then works. I assume this is not the best approach or I would do a pull request.

Thanks!

**Comment by maxcountryman** [comment]
It works fine for me, using `bcrypt` 2.0.0 on Python 2 and 3. Please give us more details about your setup.

**Comment by sphildreth** [comment]
Python 3.5, Bcrypt 2.0.0

    p = 'hunter'
    h = bcrypt.generate_password_hash(p)
    d = bcrypt.check_password_hash(h, p)

    return bcrypt.hashpw(password, bcrypt.gensalt(rounds))
    TypeError: hashpw() argument 1 must be str, not bytes

**Comment by maxcountryman** [comment]
We already check this case here: https://github.com/maxcountryman/flask-bcrypt/blob/master/test_bcrypt.py#L30-L33.

The tests work for me on Python 3.5. Are you sure there isn't something else involved here?

**Comment by ntcong** [comment]
the test doesn't pass for me
```
E       TypeError: hashpw() argument 1 must be str, not bytes

flask_bcrypt.py:163: TypeError
============================================================= 5 failed, 1 passed in 0.22 seconds =============================================================
```

**Comment by ntcong** [comment]
oh, I figured out the problem. Somehow pip freeze thinks I had py-bcrypt instead of bcrypt and tried to install py-bcrypt when I upgrade to python 3.5

**Comment by maxcountryman** [comment]
You should uninstall py-bcrypt I think. Thanks for updating us!

**Comment by sphildreth** [comment]
I fixed my issue like this:

pip uninstall flask-bcrypt
pip uninstall bcrypt
pip install flask-bcrypt --ignore-installed --no-cache-dir

Thanks!
