### ISSUE TITLE
Python3 support 

### ISSUE THREAD

**Issue by khertan** [maxcountryman/flask-bcrypt#38]
Hi,

It s look like bcrypt library changes, as i got this error :

TypeError: hashpw() argument 1 must be str, not bytes

**Comment by woosungchu** [comment]
this error still exist

**Comment by smewp** [comment]
For a long time, using Python 3, I also could not upgrade to 0.7.1 due to encoding/decoding problems. Finally got it working last week. To make it work the `set_password` method must use the `.decode('utf-8')`.  This was definitely not clear in any part of documentation or source.

    class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""
        __tablename__ = 'users'
        username = Column(db.String(80), unique=True, nullable=False)
        email = Column(db.String(80), unique=True, nullable=False)
        #: The hashed password
        password = Column(db.String(128), nullable=False)

        def __init__(self, username, email, password, **kwargs):
        """Create instance."""
            super().__init__(username=username, email=email, password=password, **kwargs)
            self.username = username
            if self.password:
                self.set_password(self.password)

        def set_password(self, password):
        """Set password."""
             self.password = bcrypt.generate_password_hash(password).decode('utf-8')

        def check_password(self, value):
        """Check password."""
            return bcrypt.check_password_hash(self.password, value)
