### ISSUE TITLE
Update documentation for python3 import

### ISSUE THREAD

**Issue by petar-andrejic** [maxcountryman/flask-bcrypt#51]
[Documentation](https://flask-bcrypt.readthedocs.io/en/latest/) suggests importing via
```
from flask.ext.bcrypt import Bcrypt
```

However attempting to do so in python3 shows that this is deprecated. Correct python3 import is 
```
from flask_bcrypt import Bcrypt
```

**Comment by maxcountryman** [comment]
Closed by #50.
