### ISSUE TITLE
pypi not updated

### ISSUE THREAD

**Issue by xavitorne** [maxcountryman/flask-bcrypt#53]
Hello,
it seems pypi is not updated with the lastest source version. I installed flask-bcrypt with pip and i don't find the implementation of the BCRYPT_HASH_PREFIX in the installed version with pypi.
Is it possible to update pypi? Thanks

**Comment by ToastyBiggums** [comment]
It seems the pip version also doesn't have this implemented.

**Comment by mahenzon** [comment]
resolved in #66 
waiting for merge

**Comment by mahenzon** [comment]
Hi! maintainer declined to deploy sources to PyPI and suggests installing the lib from GitHub. But if you still wanna install from PyPI, you can use https://pypi.org/project/Bcrypt-Flask/ (`pip install Bcrypt-Flask`). Other things are the same (imports in python are unchanged) - it's the fork I tried to bring here for autodeploy https://github.com/mahenzon/flask-bcrypt

**Comment by alanhamlett** [comment]
Version 1.0.0 was released today.
