### ISSUE TITLE
Invalid Salt

### ISSUE THREAD

**Issue by liquidpeachy** [maxcountryman/flask-bcrypt#74]
I'm getting an "Invalid Salt" error when I try to compare the hashed password with the entered password. I have used ".decode(‘utf-8’)" as stated in the docs. My code:

`pw_hash = bcrypt.generate_password_hash(form.password.data).decode('utf8')
 print(bcrypt.check_password_hash(form.password.data,pw_hash))`

I'm just using "print" to see it return true. Anyone got any ideas?

**Comment by alanhamlett** [comment]
Should be fixed in the latest release v1.0.0.
