### ISSUE TITLE
Why does the PyPI provided `0.7.1` "latest" release still use `str_safe_cmp` but the latest code here uses `hmac...`?

### ISSUE THREAD

**Issue by portante** [maxcountryman/flask-bcrypt#75]
Is this case of a bad release, where the new version used the wrong tag?

**Comment by fritsvt** [comment]
Seems like the chances made in the last few years were just never released. 0.7.1 was released in 2015 judging by the commits and pypi release history.

**Comment by portante** [comment]
If you download the latest PyPI release, do you see the latest code?  I was not able to see it.

**Comment by fritsvt** [comment]
No, like I said. 0.71.1 is the latest release and that was released back in 2015. Not sure why they've made changes to master over the years but not published a release since then.

**Comment by goodnewsj62** [comment]
wanted to open same isssue but checked the code and it has been changed but i have the latest installed version installed

**Comment by bcbecker** [comment]
Figured I'd chime in, as I'm noticing this deprecation warning as well. The switch to hmac was made in PR #70 , as mentioned, but the changes don't appear to have made it to release. 0.7.1 is latest as of current.

**Comment by psongers** [comment]
FYI `str_safe_cmp` has been removed on the latest version of Werkzeug `2.1.0` as of today. So this library on PyPi doesn't work correctly anymore unless you pin/downgrade Werkzeug version

**Comment by junqfisica** [comment]
Same problem here with `str_safe_cmp`. Is there an estimation of when a new version will be released at PyPi?

**Comment by ggsdc** [comment]
@maxcountryman any plans on releasing a new version to pypi?

**Comment by alanhamlett** [comment]
Version 1.0.0 was released today.
