### ISSUE TITLE
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'

### ISSUE THREAD

**Issue by Joe-Heffer-Shef** [maxcountryman/flask-bcrypt#86]
Werkzeug released [v2.1.0](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) recently, removing `werkzeug.security.safe_str_cmp`

See this issue:
https://stackoverflow.com/questions/71652965/importerror-cannot-import-name-safe-str-cmp-from-werkzeug-security

**Comment by alanhamlett** [comment]
What version of Flask-Bcrypt are you using? This should have been fixed in 1.0.0 with #70.

**Comment by Joe-Heffer-Shef** [comment]
Thanks, this seems to be resolved in the new versions of these packages.
